### ISSUE TITLE
Update the App to allow to read chapters

### ISSUE THREAD

**Issue by donenoyes** [flamyoad/Honnoki#1]
the app is great! Wish you could maintain it and allow to read chapters on it.

Great work. Thank you.

**Comment by flamyoad** [comment]
lol thanks mate. But I am now currently focusing on another project. So I might come back to this sooner or later.

I recommend https://github.com/tachiyomiorg/tachiyomi if you're just looking for a good manga reader

**Comment by donenoyes** [comment]
I was more looking into this project for learning purpose. Thank you, hope to see you come back soon to this project!
